title: New Language Project (WT)
author:
  name: Garbaz
  email: garbaz@t-online.de
description: >
  The goal is to create an oligosynthetic language, written logographically and with each
  morpheme pronounced as a unique syllable, with a system of grammar which allows for flexibly
  and directly transcribing thought, with minimal required structure.

remote_theme: jekyll/minima
minima:
  skin: dark
  date_format: "%Y-%m-%d"
